name: "Renovate PR Check"
description: "Run Renovate dry-run and post results as PR comment"

inputs:
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: qoomon/actions--context@v5
      id: additional-context

    - name: Run Renovate
      id: renovate
      shell: bash
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ inputs.github-token }}
      run: |
        TMP_FILE=$(mktemp)
        yarn renovate --dry-run --token "${{ inputs.github-token }}" --platform=local 2>&1 | tee "$TMP_FILE" || EXIT_CODE=$?
        echo "renovate_output<<EOF" >> $GITHUB_OUTPUT
        cat "$TMP_FILE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        exit $EXIT_CODE

    - name: Find Comment
      uses: peter-evans/find-comment@v4
      id: fc
      continue-on-error: true
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: "<!-- comment-slug: renovate-pr-comment -->"

    - name: Create or Update Comment
      uses: peter-evans/create-or-update-comment@v5
      continue-on-error: true
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          ## Renovate dry run results[^1]

          <details>
          <summary>Click to expand Renovate output</summary>

          ```bash
          ${{ steps.renovate.outputs.renovate_output }}
          ```

          </details>

          <!-- comment-slug: renovate-pr-comment -->
          [^1]: This comment was automatically generated by [this job](${{ steps.additional-context.outputs.job_url }}).
