name: "Setup Node.js"
description: "Setup Node.js with corepack and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: ".nvmrc"

    - name: Enable Corepack
      shell: bash
      run: corepack enable && corepack install

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
