name: "Setup Node.js"
description: "Setup Node.js with mise, corepack, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
      with:
        install: true
        cache: true

    - name: Enable Corepack
      shell: bash
      run: |
        corepack enable
        corepack install
        # Regenerate shims so mise picks up the corepack-managed yarn
        mise reshim

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
