name: "Setup Node.js"
description: "Setup Node.js with mise, corepack, and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true

    - name: Enable Corepack
      shell: bash
      run: corepack enable && corepack install

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
