# ref: https://yarnpkg.com/configuration/yarnrc

compressionLevel: 0

defaultSemverRangePrefix: "~"

enableGlobalCache: true

supportedArchitectures:
  os:
    - current
  cpu:
    - current

enableConstraintsChecks: true

enableTelemetry: false

logFilters:
  - code: YN0013
    level: discard

  # While a real warning, this pops up a ton because of how we're
  # hoisting versions today that doesn't indicate a real problem. To
  # avoid warning fatigue, we disable it.
  - code: YN0002
    level: discard

nmMode: hardlinks-local
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"
