name: check

on:
  push:
    branches:
      - main
  pull_request: {}

# when running in a PR, cancel in progress, use the same group
# when not, use the sha so every commit gets built and not cancelled
# don't use concurrency at the job level, it's not guaranteed
concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.sha }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack
        run: corepack enable && corepack install

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run checks
        run: yarn check
  renovate:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/renovate-pr.yml
    secrets: inherit

