name: Renovate PR Check

on:
  workflow_call: {}

jobs:
  renovate:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - id: get-job-url
        uses: pl-strflt/job-summary-url-action@v1
        continue-on-error: true
        with:
          job: 'renovate'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack
        run: corepack enable && corepack install

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Renovate
        id: renovate
        env:
          LOG_LEVEL: debug
        run: |
          yarn renovate --dry-run --token "${{ secrets.GITHUB_TOKEN }}" --platform=local renovate-output.txt 2>&1 | tee renovate-output.txt || EXIT_CODE=$?
          echo "renovate_output<<EOF" >> $GITHUB_OUTPUT
          cat renovate-output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $EXIT_CODE

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        continue-on-error: true
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- comment-slug: renovate-pr-comment -->'

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        continue-on-error: true
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## Renovate dry run results[^1]

            <details>
            <summary>Click to expand Renovate output</summary>

            ```bash
            ${{ steps.renovate.outputs.renovate_output }}
            ```

            </details>

            <!-- comment-slug: renovate-pr-comment -->
            [^1]: This comment was automatically generated by [this job](${{ steps.get-job-url.outputs.job-url }}).
